#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: terraform
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa <Your-ssh-pub-key-here>

# Downloads the iperf3 package
packages:
  - [libiperf0, 3.6]
  - [iperf3, 3.6]

# Runs iperf3
runcmd:
  - iperf3 -s -J -D > dust-${region}-throughput-server-send.1.log
  - iperf3 -s -J -D -p 5202 > dust-${region}-throughput-server-receive.1.log
